# Generated by Django 2.2.5 on 2020-01-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200130_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orer_total',
            new_name='total',
        ),
    ]
